name: Build and Tests

on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
        
      
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore STINProject.sln

      - name: Build Solution
        run: |
          msbuild.exe STINProject.sln /p:platform="Any CPU" /p:configuration="Release"
        
      - name: Run Tests
        run: vstest.console.exe .\XUnitTestProject1\bin\Release\net48\XUnitTestProject1.dll
        
      - name: Coverlet coverage test
        uses: b3b00/coverlet-action@1.2.2
        with:
          output: .\lcov.info

